travis:
  secure:
    BINSTAR_TOKEN: Lp2xOPKt2JCzPlOphCcm84+B7Si+Yn3iKxPW6DWz1LWswnLW6+E8kajMhGANzMD8nCvmBdieO4O6jFc9VSJ35lReKF7hrlTAxdPY8boHqwyO8hj02hGEfxU6gDEDFmQucaOxB8K+LbhBngr5zcBFYT5Jcr3VsWZZs4y2XDg3q5i3ZwoHJxmKNCQsHR+CdAKvhckW0acHbJLa+K4pyYNU2ccJCAiH1t1pWWmOkGjJKK5rpQfcTS24NkoowIN94W0imrl+jAGOvW6q7XxXt+G5y3Dbj0viLmiqkv2aOmhpnydkZtgL7z4evrx//CUXQxRdHL3DDGqAaHOpPIw6eBCTQWW/MNyjPi4ZjYdGdc6LgB3QZTtV9lAMudqd8GUxr2hLy9JBKfg3/vYYLKiFNhthcr5BXSNgbq/G2x6EYX8/erW83xoHuZmU6RHhe0uV/HiFIavjccATj0pCAQ8A/ZmSHOsX5CbcBnJU6/GH0a4iKECmItTfmXlICKZYz04l0ym1iwbyMxK+BWtRoR4l3AVQCYaDXMXWZQ+RHP55u4wUuQQXng5OTaEWxTvAVHudCzvUY3cOuf7LLFfeKU3ScDSqFZl48Ao4kLRcVK/B15swJbRIyLAzTV5iJuzy7S+GUHm8TlqX5wkhls3B1TzlKIIzArUw2PTuAKjB3xi+9XCUlxA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
