travis:
  secure:
    BINSTAR_TOKEN: Ew5jMChL0js6zZz5Dxji+JMPsYheUeYyPoM+N6uQVj73I3ubA19hzzFrYtMGxA/coRC5/FbtjooMrFsB2W24af0ioRoNAIdi4ZTH6HZnEOZC0y+NHsqtnWGcoXHlsyGQiFC3zdpN+UuKFXyF7Rn2twpFn8u6BE54Ovm6UrLBgxm7WhoIj5eWWjHrgJc6bJL1IDj2L/1UFB5F7lPHbYrWJsXnPlm/2Y0+SfvHnWopQFPxhUDdqpQ8VoY9MU3kRi+ZzKYvvPuifsUkd4H87idc233Q9y7Gt9DjbjccCRspzhhdNiLLHirzYFrb0zGdNuPb0p0y7N48S4lIuSKV0Wij254LzK31njXZQWlFN39C+czylDJUJ3btmZUBOxQAcZLBeKYLW2zeHiRUXCjLZBtMr8VR1oLnj0fKOxD1zaqPWPqnhf1/0GtYAEtICEV4XLTZjW6DRNien+Nzglwg8LR48rrhAhaq5+wotoGaguLh6v1fO0FbploX1Oph7FA2InYM15n0N7Zjuv9kFHZ3f0dbGNOcdEYA8OOJWxqdR8RGR/63melnmSZx3VgBEiAGPa7p6nGxbeYBfhI1RUj+i4oWsHCvgX+MTQTUU26xY6mwQshGvr9oLVDDGJ/HW3UOhyXX5mY7MlzyDpETOhP1e0LncflE0ksic8HoqBzb8Cd9u8s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
